name: Python CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest

      - name: Lint with flake8
        run: flake8 . --max-line-length=88 --exclude=.venv

  deploy:
    runs-on: ubuntu-latest
    needs: build-test-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.1.82 >> ~/.ssh/known_hosts

      - name: Deploy to Server via SSH
        run: |
          scp -r . jsvander@192.168.1.82:/home/user/my-python-app
          ssh jsvander@192.168.1.82 << 'EOF'
            cd /home/user/my-python-app
            docker stop my-python-app || true
            docker rm my-python-app || true
            docker build -t my-python-app .
            docker run -d -p 80:5000 --name my-python-app my-python-app
          EOF
