name: CI on Self-Hosted Runner

on:
  push:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python virtual environment
        run: |
          python3.12 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest

      - name: Lint
        run: |
          source .venv/bin/activate
          flake8 . --max-line-length=88 --exclude=.venv

  deploy:
    runs-on: self-hosted
    needs: build-test-lint
    steps:
      - uses: actions/checkout@v3

      - name: Rebuild and run container
        run: |
          docker stop my-python-app || true
          docker rm my-python-app || true
          docker build -t my-python-app .
          docker run -d -
