name: CI on Self-Hosted Runner

on:
  push:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Lint
        run: flake8 . --max-line-length=88 --exclude=.venv

  deploy:
    runs-on: self-hosted
    needs: build-test-lint
    steps:
      - name: Rebuild and run container
        run: |
          docker stop my-python-app || true
          docker rm my-python-app || true
          docker build -t my-python-app .
          docker run -d -p 80:5000 --name my-python-app my-python-app
