name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest

      - name: Lint with flake8
        run: |
          echo "Running lint checks..."
          flake8 . --max-line-length=88 --exclude=.venv

      - name: Simulated Deployment Step
        run: |
          echo "Simulating deployment step..."
          mkdir -p deploy_output
          cp app.py requirements.txt deploy_output/
          echo "Deployment package created:"
          ls -l deploy_output/
