name: Secure CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build-test-lint:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Lint
        run: flake8 . --max-line-length=88 --exclude=.venv

  deploy:
    if: github.actor == 'kesslar' && github.ref == 'refs/heads/main'
    needs: build-test-lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build and deploy container
        run: |
          docker stop my-python-app || true
          docker rm my-python-app || true
          docker build -t my-python-app .
          docker run -d -p 80:5000 --name my-python-app my-python-app
