name: Secure CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build-test-lint:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python virtual environment
        run: |
          python3.12 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
      - name: Lint
        run: |
          source .venv/bin/activate
          flake8 . --max-line-length=88 --exclude=.venv
  deploy:
    if: github.actor == 'kesslar' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    needs: build-test-lint
    steps:
      - uses: actions/checkout@v3

      - name: Rebuild and run container
        run: |
          docker stop my-python-app || true
          docker rm my-python-app || true
          docker build -t my-python-app .
          docker run -d -p 80:5000 --name my-python-app my-python-app