name: Secure CI/CD

on:
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Lint
        run: flake8 . --max-line-length=88 --exclude=.venv
